stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  image: sbtscala/scala-sbt:graalvm-ce-22.3.3-b1-java11_1.9.8_3.3.1
  stage: build
  script:
    - sbt compile

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "skip testing now..."
